//AUTH CONSTANTS
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const DELETE_SUCCESS = 'DELETE_SUCCESS';

export const DELETE_ERROR = 'DELETE_ERROR';

//BUCKETLIST CONSTANTS
export const ITEM_CREATED = 'ITEM_CREATED';

export const ITEM_ADDED = 'ITEM_ADDED';

export const ITEM_UPDATED = 'ITEM_UPDATED';

export const ITEM_DELETED = 'ITEM_DELETED';

export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';

export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';

export const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';

export const DISPLAY_ITEMS = 'DISPLAY_ITEMS';

export const DELETE_ITEM = 'DELETE_ITEM';

//LOCATION CONSTANTS
export const GET_USER_LOCATION = 'GET_USER_LOCATION';

//RECOMMENDATION CONSTANTS
export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS'

export const RECOMMENDATIONS_TO_LIST = 'RECOMMENDATIONS_TO_LIST'

export const RECOMMENDATIONS_ERROR = 'RECOMMENDATIONS_ERROR'